# Generated by Django 5.1.7 on 2025-03-17 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('image_name', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('fats', models.FloatField(blank=True, null=True)),
                ('carbohydrates', models.FloatField(blank=True, null=True)),
                ('sugar', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('serving_size', models.FloatField(blank=True, null=True)),
                ('serving_size_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('energy_100g', models.FloatField(blank=True, null=True)),
                ('saturated_fat_100g', models.FloatField(blank=True, null=True)),
                ('trans_fat_100g', models.FloatField(blank=True, null=True)),
                ('calcium_100g', models.FloatField(blank=True, null=True)),
                ('iron_100g', models.FloatField(blank=True, null=True)),
                ('vitamin_a_100g', models.FloatField(blank=True, null=True)),
                ('vitamin_c_100g', models.FloatField(blank=True, null=True)),
                ('cholesterol_100g', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
