# Generated by Django 5.1.7 on 2025-03-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_ocrresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionresult',
            name='extracted_text',
        ),
    ]
