# Generated by Django 5.1.7 on 2025-04-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='ingredients_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='history',
            name='nutrition_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='history',
            name='total_result',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
