# Generated by Django 5.1.7 on 2025-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_history_ingredients_data_history_nutrition_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='analysis_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
